# Python fundamentals

### Data types

In [2]:
a = 5
print(type(a))

<class 'int'>


In [3]:
a = 5.0
print(type(a))

<class 'float'>


In [4]:
a = '5'
print(type(a))

<class 'str'>


In [5]:
a = True
print(type(a))

<class 'bool'>


## Containers

In [6]:
a_list = [1, 2, 2, 3.0, '5']
print(a_list)
print(type(a_list))

[1, 2, 2, 3.0, '5']
<class 'list'>


In [7]:
a_set = set(a_list)
print(a_set)
print(type(a_set))
a_set = {1, 2, 3, 4}
print(a_set)

{'5', 1, 2, 3.0}
<class 'set'>
{1, 2, 3, 4}


In [8]:
a_dict = {
    1: 'unu',
    'doi': 2,
    3.0: a_set
}
print("Keys:\t", list(a_dict.keys()))
print("Values:\t", list(a_dict.values()))
print(a_dict)
print(type(a_dict))

Keys:	 [1, 'doi', 3.0]
Values:	 ['unu', 2, {1, 2, 3, 4}]
{1: 'unu', 'doi': 2, 3.0: {1, 2, 3, 4}}
<class 'dict'>


## Functions

In [9]:
def add_two_values(a, b):
    return a + b

add_two_values(5, 6)

11

In [10]:
def multiply(a: float, b: float) -> float:
    return a * b

multiply(4.0, 5.0)

20.0

In [11]:
multiply("AB", 2)

'ABAB'

# Numpy

Check: https://numpy.org/doc/stable/user/absolute_beginners.html

### Installing 3rd party libraries

In [12]:
%pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.6 MB 6.9 MB/s eta 0:00:02
   -------- ------------------------------- 2.6/12.6 MB 7.1 MB/s eta 0:00:02
   ------------ --------------------------- 3.9/12.6 MB 7.2 MB/s eta 0:00:02
   ----------------- ---------------------- 5.5/12.6 MB 7.2 MB/s eta 0:00:01
   ----------------------- ---------------- 7.3/12.6 MB 7.4 MB/s eta 0:00:01
   ---------------------------- ----------- 8.9/12.6 MB 7.4 MB/s eta 0:00:01
   --------------------------------- ------ 10.5/12.6 MB 7.4 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 7.6 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 7.5 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [13]:
%pip install timed-decorator

Note: you may need to restart the kernel to use updated packages.


In [14]:
import numpy as np
from math import sqrt
from timed_decorator.simple_timed import timed

In [15]:
x = np.random.uniform(low=-5.5, high=5.5, size=(50,))
x

array([-4.53178086,  0.14633282,  0.20315039,  5.31636987, -3.57485897,
        1.40372454, -0.67195875, -5.27090279, -3.51653732, -3.97795741,
        4.98627083, -0.62810916,  2.4429018 ,  4.30425418,  2.79766179,
       -0.90006995, -5.23713257, -4.86737752, -5.19395223, -1.25355008,
       -3.39220802, -1.7173688 , -3.63902186,  3.4491246 , -1.33074818,
        3.86027475,  1.65390252, -0.43550791, -5.47478867, -1.08694294,
       -0.4557651 ,  2.29422498, -1.40270937, -4.5684643 , -1.86120718,
        2.78338833,  4.25948188,  5.37100251,  2.77726898, -4.65643259,
        4.1740738 , -1.75150144, -0.83458639, -3.05908082,  2.75309715,
       -3.54149538,  3.32501989, -1.13590795, -2.8628665 ,  2.87426898])

In [16]:
x > 0

array([False,  True,  True,  True, False,  True, False, False, False,
       False,  True, False,  True,  True,  True, False, False, False,
       False, False, False, False, False,  True, False,  True,  True,
       False, False, False, False,  True, False, False, False,  True,
        True,  True,  True, False,  True, False, False, False,  True,
       False,  True, False, False,  True])

In [17]:
x[x > 0]

array([0.14633282, 0.20315039, 5.31636987, 1.40372454, 4.98627083,
       2.4429018 , 4.30425418, 2.79766179, 3.4491246 , 3.86027475,
       1.65390252, 2.29422498, 2.78338833, 4.25948188, 5.37100251,
       2.77726898, 4.1740738 , 2.75309715, 3.32501989, 2.87426898])

In [19]:
list(x)

[np.float64(-4.531780861214501),
 np.float64(0.14633281683842636),
 np.float64(0.20315038853590206),
 np.float64(5.316369868567614),
 np.float64(-3.5748589715955537),
 np.float64(1.4037245350620555),
 np.float64(-0.6719587542442103),
 np.float64(-5.27090278690007),
 np.float64(-3.5165373210422444),
 np.float64(-3.9779574112099),
 np.float64(4.986270825751154),
 np.float64(-0.6281091584676934),
 np.float64(2.4429018001320193),
 np.float64(4.304254182383499),
 np.float64(2.7976617868711458),
 np.float64(-0.9000699546805357),
 np.float64(-5.237132565798531),
 np.float64(-4.867377522988171),
 np.float64(-5.193952229885799),
 np.float64(-1.253550082638621),
 np.float64(-3.392208022569366),
 np.float64(-1.7173687961597048),
 np.float64(-3.6390218614250047),
 np.float64(3.4491245966386668),
 np.float64(-1.3307481803055223),
 np.float64(3.860274752451419),
 np.float64(1.6539025209034026),
 np.float64(-0.43550791112918663),
 np.float64(-5.474788670471965),
 np.float64(-1.0869429443249157),
 np.

## Comparing numpy arrays to python lists

In [21]:
@timed(show_args=True, use_seconds=True)
def normalize_np(x: np.ndarray) -> np.ndarray:
    mean = np.mean(x)
    std = np.std(x)
    return (x - mean) / std

@timed(show_args=True, use_seconds=True)
def normalize_py(x: list) -> list:
    mean = sum(x) / len(x)
    var = sum([(i - mean) ** 2 for i in x]) / len(x)
    std = sqrt(var)
    return [(i - mean) / std for i in x]

x = np.random.uniform(low=-5.5, high=5.5, size=(50000,)).astype(np.float64)
y = list(x)
normalized_x = normalize_np(x)
normalized_y = normalize_py(y)
assert np.allclose(normalized_x, normalized_y)

normalize_np(ndarray(50000,)) -> total time: 0.000562400s
normalize_py(list(float64)[50000]) -> total time: 0.008573700s


#### Python is slower than numpy in general

In [22]:
%%timeit

np.min(x)

6.72 μs ± 106 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [23]:
%%timeit

min(y)

450 μs ± 4.46 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [24]:
a = np.random.uniform(low=-5.5, high=5.5, size=(50,)).astype(np.float64)
b = list(a)


In [25]:
%%timeit

np.min(a)

1.42 μs ± 10.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [26]:
%%timeit

min(b)

497 ns ± 3.26 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


## Inplace operations
Use them when you can safely modify the input

In [27]:
@timed(show_args=True, use_seconds=True)
def normalize_np_(x: np.ndarray) -> np.ndarray:
    mean = np.mean(x)
    std = np.std(x)
    x -= mean
    x /= std
    return x

In [ ]:
x = np.random.rand(1000, 20000)

# This creates a copy
y = normalize_np(x)
assert not np.allclose(x, y)

# Inplace operations modify the original array! But they are faster and use less memory.
z = normalize_np_(x)
assert np.array_equal(x, z)

normalize_np(ndarray(1000, 20000)) -> total time: 0.189661978s
normalize_np_(ndarray(1000, 20000)) -> total time: 0.139641280s
